//
//  NotifyManager.h
//  Notify
//
//  Created by shahzin ks on 21/09/12.
//  Copyright (c) 2012 Notikum. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <CoreLocation/CoreLocation.h>

/*
 * Notify Manager is the singleton object responsible for handling notify operations and events
 */

@interface NotifyManager : NSObject<CLLocationManagerDelegate,UIAlertViewDelegate>{

}

+(NotifyManager *)sharedManager;

/**
 * Starts the notiphi service in the background
 */
-(void) startNotifyServicesWithAppID:(NSString *)appID key:(NSString *)key;


/**
 * Shows an alert seeking the permission of the user
 */

-(void) seekUserPermissionForNotifyServiceWithTitle:(NSString *)title message:(NSString *)message;

/**
 * Stops all notiphi services running in the background
 */

-(void) stopNotifyServices;


/**
 * Process the local notification generated by notiphi
 */
-(void) processLocalNotification:(UILocalNotification *)localNotification;


/**
 * Process the remote notification generated by notiphi
 */
-(void) processRemoteNotification:(NSDictionary *)userInfo;


/**
 * Process the launch options to verify whether the app was launched by notiphi services
 */
-(void) processLaunchOptions:(NSDictionary *)launchOptions;


/**
 * Return YES if the local notification was generated by notiphi
 */

-(BOOL) isLocalNotificationFromNotify:(UILocalNotification *)localNotification;

/**
 * Return YES if the remote notification was recieved from notiphi
 */
-(BOOL) isRemoteNotificationFromNotify:(NSDictionary *)userInfo;

/**
 * Return YES if the app was launched by notiphi services
 */
-(BOOL) isAppLaunchedByNotifyService:(NSDictionary *)launchOptions;


/**
 * Register the device with notiphi services for push notification
 */
-(void) registerForPushNotificationUsingDeviceToken:(NSData *)deviceToken;

@end
